version: "3.9"

services:
  api:
    build: .
    container_name: securepost_api
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASS: 123123
      DB_NAME: secure_post
      JWT_SECRET: jsonsecretkeyshouldnotsharewithanyone
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    container_name: securepost_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123123
      MYSQL_DATABASE: secure_post
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
